---
- name:
  hosts: windows

  tasks:
   - name: Create a new domain group
     win_domain_group:
      name: developers
      scope: domainlocal
      category: security
      description: Developers Group
      state: present
      ignore_protection: yes
   - name: Creating a new user
     win_domain_user:
        name: Belk
        firstname: Sylvestre
        surname: SB
        password: Accel2021@
        state: present
        
        street: virage
        city: dakar
        state_province: senegal
        postal_code: 12000
        country: DK
        attributes:
          telephoneNumber: 772247049
   - name: Adding Mbaye to a Administrateurs
     win_domain_group_membership:
       name: Administrateurs
       members: 
        - Mbaye
       state: present
   - name: Adding Mbaye to Utilisateurs du Bureau à distance
     win_domain_group_membership:
       name: Utilisateurs du Bureau à distance
       members: 
        - Mbaye
       state: present

         
