---
- name:
  hosts: windows

  tasks:
   - name: Create a new domain group
     win_domain_group:
      name: developers
      scope: domainlocal
      category: security
      description: Developers Group
      state: present
      ignore_protection: yes
   - name: Creating a new user
     win_domain_user:
        name: Mbaye
        firstname: Alioune
        surname: ABM
        password: Accel2021@
        groups:
         - Administrateurs de l’entreprise
         - Utilisateurs du Bureau à distance
        street: virage
        city: dakar
        state_province: senegal
        postal_code: 12000
        country: DK
        
        attributes:
          telephoneNumber: 772247049