---
- name: Manage Updates on Systems
  hosts: windows
  vars:
    log_file: C:\Windows\Temp\ansible_available_updates.txt
    access_token: ""

  tasks:
    - name: Microsoft update servers are queried
      win_updates:
        category_names: CriticalUpdates
        state: searched
        log_path: "{{ log_file }}"

    - name: Available Critical updates are captured
      win_shell: "type {{ log_file }}"
      register: file_output

    - name: Available updates found
      debug:
        msg: "Available updates found!"
      when: "'Adding update' in file_output.stdout"

    - name: critical updates are applied
      win_updates:
        category_name: CriticalUpdates
      register: updates_status

    - name: Server is rebooted
      win_reboot:
      when: updates_status.reboot_required
   